import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="text-black pl-8 pr-8 md:pl-12 md:pr-12 bg-slate-100 h-screen overflow-scroll text-sm">
					<div className="h-full flex flex-col">
						<nav className="flex flex-row items-center bg-teal-300 p-2 gap-2">
							<Link
								href="/"
								passHref
							>
								<h1 className="cursor-pointer hover:opacity-50 hover:underline">
									Prisma Accelerate Hacker News Clone
								</h1>
							</Link>
							<Link
								href="/submit"
								className="cursor-pointer hover:opacity-50 hover:underline border-l-2 border-black pl-2"
							>
								new post
							</Link>
							<a
								href="https://www.prisma.io/data-platform/accelerate?utm_source=accelerate-hacker-news"
								target="_blank"
								rel="noopener noreferrer"
								className="cursor-pointer hover:opacity-50 hover:underline border-l-2 border-black pl-2"
							>
								what is Prisma Accelerate?
							</a>
							<a
								href="https://prisma.io?utm_source=accelerate-hacker-news"
								target="_blank"
								rel="noopener noreferrer"
								className="cursor-pointer hover:opacity-50 hover:underline border-l-2 border-black pl-2 grow"
							>
								prisma.io
							</a>
							<a
								href="https://console.prisma.io?utm_source=accelerate-hacker-news"
								target="_blank"
								rel="noopener noreferrer"
								className="cursor-pointer hover:opacity-50 hover:underline"
							>
								login
							</a>
						</nav>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
